title: Local Legend FC
description: Small Club, Big Dreams. A paid upfront retro indie football management game.
url: https://locallegendfc.com
baseurl: ""
markdown: kramdown
plugins: []
exclude:
  - README.md

defaults:
  - scope:
      path: ""
    values:
      layout: default
